services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: php artisan migrate --force && php artisan config:cache && php artisan serve --host=0.0.0.0 --port=8080

